spring.application.name=sb-ecom

# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
# spring.datasource.username=postgres
# spring.datasource.password=admin@123

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/
server.port=${PORT:8080}

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom



#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG


# Needed if you are using elastic beanstalk
#server.port=5000
# For localhost
# frontend.url=http://localhost:5173/
# image.base.url=http://localhost:8080/images

frontend.url=https://ecommerce-website-snowy-eight.vercel.app
image.base.url=https://ecommerce-website-c66t.onrender.com/images

#STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}

cloudinary.cloud_name=spsnpcmr
cloudinary.api_key=889892162193872
cloudinary.api_secret=fVPMKuWGrnID6rCtGG_39lQsfb0